name: Run Custom Script

on:
  workflow_dispatch

jobs:
  run_script_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x my-script.sh

      - name: Run custom script
        run: ./my-script.sh
